### ISSUE TITLE
Issue when using React Components as props 

### ISSUE THREAD

**Issue by fastndead** [eliasm307/storybook-addon-deep-controls#11]
Hi there! Love this addon, it is really helpful! That being said I came across one issue that forces me to disable it on some stories.

Here's a simplified version of my config for a story:
```ts
export const WithIcon: Story = {
  parameters: {
    deepControls: { enabled: true },
  },
  args: {
    icon: <ArrowsArrowUp />,
  }
}
```

this causes this error:
<img width="1214" alt="image" src="https://github.com/eliasm307/storybook-addon-deep-controls/assets/33729448/05fe99ec-c2cf-43c3-83f4-8624af9afc6b">

here's the code that breaks:
<img width="856" alt="image" src="https://github.com/eliasm307/storybook-addon-deep-controls/assets/33729448/69f3bd89-7a50-43c9-b696-33b3d09618bc">

I didn't look too much in the code side, but I'm sure that the issue is in the react component being passed as a prop because when i disable deepControls the issue disappears and also if i keep deepControls enabled and remove the icon arg issue disappears also.

**Comment by eliasm307** [comment]
Hey @fastndead I've published v0.6.2 with a fix for this, let me know if this resolves your issues

**Comment by fastndead** [comment]
Hey @eliasm307 , sorry for the delayed response, just tried v0.6.2, the issue did resolve, thank you!

**Comment by eliasm307** [comment]
@fastndead cool, thanks for the confirmation
