### ISSUE TITLE
question: TypeWithDeepControls with const meta: Meta<typeof Component> 

### ISSUE THREAD

**Issue by giovannipds** [eliasm307/storybook-addon-deep-controls#16]
Hey! Quick question, I saw the [typescript docs](https://github.com/eliasm307/storybook-addon-deep-controls?tab=readme-ov-file#typescript) and there's an example of a single story not bothering about deep `argTypes`, is it possible to use it for this scenario as well (`default` `meta` `export`) and if so, what's the approach?

Wrapping `Meta` with `TypeWithDeepControls`? If so, can we put it on the documentation? Thank you!

E.g.:

```tsx
type Story = StoryObj<typeof Component>;

const meta: Meta<typeof Component> = {
  argTypes: {
    "my.deep.object": {
      control: "select",
      description: "Its description.",
      options: ["option1", "option2"],
      table: {
        defaultValue: {summary: "option1"},
        type: {summary: "enum"},
      },
    },
  },
  parameters: {
    // ...
  },
  title: "My Title",
};

export default meta;

export const Default: Story = {
  args,
};
```

The idea is basically centralizing the `argTypes` on `meta` instead of single stories.

**Comment by giovannipds** [comment]
oh... duh! I just re-read it and it says to wrap the `Meta` lol! My bad! Thank you! Either way, I think it could be interesting putting both code scenarios to quickly check :)

**Comment by eliasm307** [comment]
Hey @giovannipds thanks for the feedback, I've updated the example
