### ISSUE TITLE
Better handle propless React elements

### ISSUE THREAD

**Issue by jared-hexagon** [eliasm307/storybook-addon-deep-controls#2]
# Issue

When you pass a React element (without any props) inside an object of a prop......

```
<MyComponent someObject={{ someElement: <MyElement /> }} />
```

 .....you get this exception:

```
index.js:232 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at filterProps (index.js:232:1)
    at parseReactElement (index.js:253:1)
    at Object.transform (index.js:308:1)
    at index.js:144:1
    at Array.map (<anonymous>)
    at Object.prettyPrint (index.js:137:1)
    at formatComplexDataStructure (index.js:303:1)
    at formatPropValue (index.js:370:1)
    at formatProp (index.js:384:1)
```

Passing any prop seems to fix it.

# Possible reason

I debugged it and it throws that error when I have a React element in an object in a prop and that element has no props provided to it:

webpack://proj/node_modules/.pnpm/react-element-to-jsx-string@15.0.0_react-dom@18.2.0_react@18.2.0/node_modules/react-element-to-jsx-string/dist/cjs/index.js

```
var filterProps = function filterProps(originalProps, cb) {
  var filteredProps = {};

  // THROWN HERE.........

  Object.keys(originalProps).filter(function (key) {
    return cb(originalProps[key], key);
  }).forEach(function (key) {
    return filteredProps[key] = originalProps[key];
  });
  return filteredProps;
};

var parseReactElement = function parseReactElement(element, options) {
  var _options$displayName = options.displayName,
      displayNameFn = _options$displayName === void 0 ? getReactElementDisplayName : _options$displayName;

  // prop.myObject.icon = <SomeElement />

  if (typeof element === 'string') {
    return createStringTreeNode(element);
  } else if (typeof element === 'number') {
    return createNumberTreeNode(element);
  } else if (! /*#__PURE__*/React__default["default"].isValidElement(element)) {
    throw new Error("react-element-to-jsx-string: Expected a React.Element, got `".concat(_typeof(element), "`"));
  }

etc.
```

Storybook 7

Disabling the extension makes the error go away (but then I have the basic JSON editor)

```
  addons: [
    '@storybook/addon-docs',
    'storybook-dark-mode',
    'storybook-css-modules',
    'storybook-addon-deep-controls'
  ],
```

**Comment by eliasm307** [comment]
hey, thanks for taking the time to raise this!

From the error messages you have provided its not clear how this package is causing the error so could you please provide more detail about how your stories are setup so I can try to reproduce this to investigate?

I am not sure where the following should be done in a story to cause the issue:

```tsx
<MyComponent someObject={{ someElement: <MyElement /> }} />
```

**Comment by eliasm307** [comment]
Hi @jared-hexagon ive not got any further details regarding this so closing the issue. Feel free to raise another issue if you have a way to demonstrate what you mean
