### ISSUE TITLE
Add option to merge custom argTypes with inferred ones

### ISSUE THREAD

**Issue by Niqp** [eliasm307/storybook-addon-deep-controls#22]
When adding something to a flattened arg's argTypes, it completely replaces the inferred ones, which means the controls disappear. Is it possible to add an option to merge the custom argTypes, when you only need to add a description, for example, but don't want to change the controls?

**Comment by eliasm307** [comment]
@Niqp thanks for the feedback

Could you please provide a code example of what you mean?

I have an example of partially defining argTypes for object properties in the docs, so I am not sure about the case you have

**Comment by eliasm307** [comment]
Hello @Niqp ill close this as no further details have been provided but can reopen if you can provide some examples of what you mean

**Comment by Niqp** [comment]
Hello @eliasm307! Sorry for the late reply. Here is an example of this issue:
https://github.com/Niqp/StorybookDeepControlsArgTypesMerge/blob/main/src/stories/Button.stories.js
When you add argTypes for the "option.primary", it loses the control, and the parameter type in the docs as well. It only works if you also supply the control type and the table description type directly in argTypes. Maybe I'm doing something wrong, can you assist, please?

**Comment by eliasm307** [comment]
@Niqp thanks for the example, I understand the problem now. I'll make a fix soon to allow merging some properties

**Comment by eliasm307** [comment]
Hey @Niqp thanks again for this idea, I've published v0.8.0 with this functionality, let me know if you have feedback

I hope you have a great week 🙂

**Comment by Niqp** [comment]
@eliasm307 Thank you very much, the feature works as intended!
One small issue I found: when the path to the property is long, it will overflow over the "raw" button. Not sure if that happens without the plugin as well:
![Screenshot 2024-09-29 at 15 52 45](https://github.com/user-attachments/assets/0571a998-f995-479c-ae33-bcf8cb984aef)

**Comment by eliasm307** [comment]
@Niqp Hey, yeah the overflow thing is not due to the addon, same happens when it is disabled, eg: 
![image](https://github.com/user-attachments/assets/877fb6d7-6d23-4ede-aa54-a67980585bcd)

You can raise this as an issue with storybook for the controls addon or the library storybook uses for rendering the json tree, ie https://github.com/shachi-bhavsar/json-editable-react-tree/tree/master
