### ISSUE TITLE
when I try to clone the repo I get an error

### ISSUE THREAD

**Issue by dannyhw** [eliasm307/storybook-addon-deep-controls#29]
error: unable to create symlink .github/LICENSE.md: File name too long
error: unable to create symlink .github/README.md: File name too long

any steps on how to get around this?

edit: I was able to get it to clone with these settings
```
git config --global core.symlinks false
git config --global core.longpaths true
```

**Comment by eliasm307** [comment]
hey, 

> I was able to get it to clone with these settings

yeah this was the solution I used

However, I've removed the symlinks now and have a script which manually syncs the github files, hopefully this solves the issue https://github.com/eliasm307/storybook-addon-deep-controls/commit/3e53116b0c04f2a83c6746fcb8a9889bb36d5fc3

I'll close this issue but let me know if you still have problems
