### ISSUE TITLE
Needs a register.js to work with React Native

### ISSUE THREAD

**Issue by prateekchachra-aily** [eliasm307/storybook-addon-deep-controls#4]
The package needs an empty register.js to work with React Native as an add on for the controls.

**Comment by AdamTyler** [comment]
👍 Would love to get this into npm package

**Comment by eliasm307** [comment]
I've published v0.4.1 with an empty register.js, let me know if that solves your issue

**Comment by eliasm307** [comment]
Hi, since there was no reply I'm gonna assume your issue is resolved.

Please raise another issue if not

**Comment by prateekchachra-aily** [comment]
Hello @eliasm307 !

I can confirm the issue was resolved! Thank you for the quick response!
