### ISSUE TITLE
Both nested object and original object are showing, is this expected?

### ISSUE THREAD

**Issue by leozhao0709** [eliasm307/storybook-addon-deep-controls#5]
Hello, thanks for this awesome addons. When I am trying this, I saw both nested object and original object are showing, is this expected?

I have the following story:

```tsx
export const TextExample: TypeWithDeepControls<Story> = {
  args: {
    children: 'Text',
    strikeThrough: {
      isActive: false,
      color: '#000',
    },
  },
  argTypes: {
    foregroundStyle: { control: 'color' },
    'strikeThrough.isActive': { control: 'boolean' },
    'strikeThrough.color': { control: 'color' },
  },
};
```

And I saw it rendered as this:

<img width="1609" alt="Snipaste_2024-02-17_17-12-18" src="https://github.com/eliasm307/storybook-addon-deep-controls/assets/10889192/c189ab67-912c-4594-96fd-b7464ee647d8">

Is this expected? Is there anyway only render the nested object only? 

Thanks again for this addon.

**Comment by eliasm307** [comment]
Hey thanks for the feedback, no that shouldn't happen. I'll try to recreate this and figure out the issue

**Comment by eliasm307** [comment]
Hi  @leozhao0709 I've tried to recreate this but I'm not getting the same issue, ie 

![image](https://github.com/eliasm307/storybook-addon-deep-controls/assets/13420359/3e520136-a497-48a6-b448-88ef5da45743)

I also notice in your example image you are not getting the same controls a defined in the code you sent, e.g. foregroundStyle is missing, so if your code is different when you get this issue please let me know.

Could you also share any storybook config files you have (with any personal bits removed) ie main.js/ts, preview.js/ts etc maybe you have another addon changing the behaviour

**Comment by eliasm307** [comment]
Also another note is please make sure the addon is enabled for your stories, its not enabled by default when you install the addon. See details on how to do that here https://github.com/eliasm307/storybook-addon-deep-controls?tab=readme-ov-file#getting-started

**Comment by eliasm307** [comment]
Also btw you can remove this argType `'strikeThrough.isActive': { control: 'boolean' },` since its a primitive type, the addon will be able to automatically guess this from your default value. You will just need to do this for special values, e.g. colours, as you have done

**Comment by leozhao0709** [comment]
@eliasm307 thanks for the quick response. I've removed foregroundStyle in my code to make the thing I saw more clearly. I set the `deepControls: { enabled: true }` in .storybook/parameters.ts.

Here's my .storybook/main.ts:

```ts
import path from 'node:path';
import type { StorybookConfig } from '@storybook/react-vite';

const config: StorybookConfig = {
  // Required
  framework: {
    name: '@storybook/react-vite',
    options: {
      builder: {
        viteConfigPath: path.join(__dirname, '../build-tools/vite.config.mts'),
      },
    },
  },
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  // Optional
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    'storybook-addon-deep-controls',
  ],
  docs: {
    autodocs: 'tag',
  },
  // staticDirs: ['../public'],
};

export default config;
```

And this is `.storybook/preview.ts`

```ts
import { Preview } from '@storybook/react';

const preview: Preview = {
  parameters: {
    deepControls: { enabled: true },
    actions: { argTypesRegex: '^on[A-Z].*' },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

export default preview;
```

**Comment by leozhao0709** [comment]
I can also share my component here:

```tsx
type TextProps = React.HTMLAttributes<HTMLSpanElement> & {
  strikeThrough?: {
    isActive: boolean;
    color?: string;
  };
};

const Text: React.FC<TextProps> = ({
  className,
  children,
  ...restProps
}: TextProps) => {

  return (
    <span {...restProps} className={classNames(className)}>
      {children}
    </span>
  );
};

Text.defaultProps = {};

export default React.memo(Text);
```

It's a pretty empty component example, but I still see both nested object and original object. Can you try this component?

**Comment by leozhao0709** [comment]
So I tried the Dev example in the repo. Seems the component type need to be **object** exactly, then it won't show the original object?

If it's like this 

```tsx
export function Dev(config: object) {
  return (
    <div>
      <h1>Config received by Component:</h1>
      <pre
        id="actual-config-json"
        style={{
          whiteSpace: 'pre-wrap',
          wordWrap: 'normal',
        }}
      >
        {JSON.stringify(config)}
      </pre>
    </div>
  );
}
```

Then it can render correctly as this:
<img width="1091" alt="1" src="https://github.com/eliasm307/storybook-addon-deep-controls/assets/10889192/cb419e35-64d0-4905-972f-b054cee0a6f8">

But if I define a Config type, then it will show the original type:

```tsx
type ConfigType = {
  someObject: {
    anyString: string;
    enumString: string;
  };
};

export function Dev(config: ConfigType) {
  return (
    <div>
      <h1>Config received by Component:</h1>
      <pre
        id="actual-config-json"
        style={{
          whiteSpace: 'pre-wrap',
          wordWrap: 'normal',
        }}
      >
        {JSON.stringify(config)}
      </pre>
    </div>
  );
}
```

This will render this:

<img width="1086" alt="2" src="https://github.com/eliasm307/storybook-addon-deep-controls/assets/10889192/705be6a0-c9d9-4cc9-897f-ad84e910d32f">

**Comment by eliasm307** [comment]
@leozhao0709 Thank you so much for the detail, it helped a lot!

So I think the issue was coming from the docs addon, which was adding in some argTypes based on your prop types. I've updated the addon to work with this, but it means you need to supply an initial value for args so the deep controls addon can determine the shape of your args. 

I've added some notes here https://github.com/eliasm307/storybook-addon-deep-controls?tab=readme-ov-file#with-the-docs-addon

Possibly also related to #3

**Comment by eliasm307** [comment]
@leozhao0709 let me know if this solves your issue then I can close this issue

**Comment by leozhao0709** [comment]
@eliasm307 it works perfectly now! Thanks for the quick fix!

**Comment by eliasm307** [comment]
@leozhao0709 great! thanks for providing detailed information so it was easier to investigate and fix
