### ISSUE TITLE
Plans for 8.0.0

### ISSUE THREAD

**Issue by jorgercg** [eliasm307/storybook-addon-deep-controls#8]
Hi there! Great work!

Are there plans to support Storybook 8.0.0?

Again, many thanks for the great work done!

**Comment by eliasm307** [comment]
Hi, yes I will once it's storybook 8 is officially released

**Comment by eliasm307** [comment]
Btw @jorgercg i tried this with the current Storybook 8 release candidate and it seemed to work without any functionality changes.

So I'll just be updating the peer dependency version range to include storybook 8.

Let me know if there is an issue you are having with storybook 8 and I can look into it before it's released next week

**Comment by jorgercg** [comment]
Yes! I have the same here, no problem whatsoever with 8.0.0. In fact, during the build process it shows a message that made me imply that it would not work, but in fact it does!

Thanks for your prompt response and for the awesome work done!

**Comment by eliasm307** [comment]
OK cool, I've now published v0.6.1 which adds storybook 8 to the allowed peer dependency versions

I'll close this issue, but if you have any issues when using v8 please raise a separate ticket

**Comment by tidemann** [comment]
Just tried to set it up with 8.0.0-rc.3:

WARN The following packages are incompatible with Storybook 8.0.0-rc.3 as they depend on different major versions of Storybook packages:
WARN - storybook-addon-deep-controls@0.6.1

**Comment by eliasm307** [comment]
@tidemann yes I've set it to accept v8 but only the official releases, not sure if I can set it to accept release candidate versions which are not written in proper semver notation

Either way, you can ignore the warning when installing, it should still work. If it doesn't then please raise an issue

**Comment by eliasm307** [comment]
When 8.0.0 is officially released you shouldn't get the install warning

**Comment by jorgercg** [comment]
Yes, 8.0 and the install warning is gone!!!!

Jorge Gonçalves
